name: Clear Cache

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 0 * * *' # Runs once a day (https://crontab.guru/once-a-day)

permissions:
  actions: write

jobs:
  clear:
    name: Clear cache
    runs-on: ubuntu-latest
    steps:
      - uses: MyAlbum/purge-cache@951302f4141da79834cd338a6349034a6edebcc2 # v3
        with:
          max-age: 1
