name: command-dispatch
on:
  issue_comment:
    types: [created]
permissions:
  contents: write
  pull-requests: write
  actions: write
#permissions: write-all
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    if: |
      contains(FromJSON('["carlspring", "steve-todorov"]'), github.triggering_actor) &&
      github.event.issue.pull_request
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: >
            [
              {
                "command": "merge-snapshot",
                "permission": "write",
                "issue_type": "pull-request"
              },
              {
                "command": "merge-release",
                "permission": "write",
                "issue_type": "pull-request"
              },
              {
                "command": "update-release",
                "permission": "write",
                "issue_type": "pull-request"
              },
              {
                "command": "deploy-pr",
                "permission": "write",
                "issue_type": "pull-request"
              },
              {
                "command": "help",
                "permission": "write",
                "issue_type": "pull-request"
              }
            ]
